services:
  nginx:
    image: nginx:1.27-alpine-slim
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/letsencrypt   # where certbot will write certs
      - ./certbot-webroot:/var/www/certbot  # ACME HTTP challenge webroot
    depends_on:
      - nextjs
      - websocket
    networks:
      - app-network

  certbot:
    image: certbot/certbot:v2.7.0
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certbot-webroot:/var/www/certbot
    entrypoint: >
      sh -c "certbot certonly
             --non-interactive
             --agree-tos
             --email you@rasmusnilsson.com
             --webroot
             --webroot-path=/var/www/certbot
             -d rasmusnilsson.com
             -d www.rasmusnilsson.com"
    networks:
      - app-network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.Nextjs
    environment:
      - NODE_ENV=production
      - WEBSOCKET_URL=${WEBSOCKET_URL}
    networks:
      - app-network

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.Websocket
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
